### ISSUE TITLE
Build cache?

### ISSUE THREAD

**Issue by utdrmac** [x1unix/docker-go-mingw#12]
Thank you for this docker image! My go program has lots of dependencies and several C libraries. These have to be compiled each time I run the container to build my app. Is there some way to compile-cache all of the dependencies?

**Comment by x1unix** [comment]
@utdrmac Go build cache is located in GOPATH.

You can mount your local host GOPATH or either create a Docker volume and mount it as GOPATH.

**Comment by utdrmac** [comment]
This doesn't appear to work:

`docker run --rm -it -v golang-windows-cache:/go/pkg -v /home/xxx/go/src/proj:/go/src/proj x1unix/go-mingw /bin/sh -c "cd /go/src/proj && make"`

Go downloads and compiles all packages every time.

**Comment by utdrmac** [comment]
Maybe permissions issue. I see /go/pkg in the container is owned by root, but /go/src/proj is owned by 1000.

**Comment by utdrmac** [comment]
Had to add GOCACHE and point to somewhere in my docker volume as it defaults to /root/.cache/go-build, which gets wiped each run.

```
docker run --rm -it \
  -v golang-windows-cache:/go/pkg \
  -v /home/test/go/src/proj:/go/src/proj \
  -e GOCACHE=/go/pkg/.cache \
  x1unix/go-mingw /bin/sh -c "cd /go/src/proj && go build -v -o proj-windows-amd64.exe"
```

**Comment by x1unix** [comment]
@utdrmac you can start container as other uid/gid with “-u” option, but volume option may be even better
