### ISSUE TITLE
Example README doesn't work as documented

### ISSUE THREAD

**Issue by utdrmac** [x1unix/docker-go-mingw#13]
Attempted to run as documented in the readme:

```
$ docker run --rm -it -v "$(pwd)":/tmp/build x1unix/go-mingw go build -v -o bakinbacon-win-x64.exe
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

I assumed based on the readme that the builder would look in /tmp/build and execute in their but that doesn't seem to be th case. I had to run it like this:

```
$ docker run --rm -it -v "$(pwd)":/tmp/build x1unix/go-mingw /bin/sh -c "cd /tmp/build && go build -v -o bakinbacon-win-x64.exe"
```

Is that the correct way?

**Comment by x1unix** [comment]
Please take a look at example: https://github.com/x1unix/docker-go-mingw/blob/master/example/sqlite-app/Makefile

**Comment by utdrmac** [comment]
Yea, I looked at that example for sqlite. That's how I got it working in the first place. Thanks!

**Comment by x1unix** [comment]
@utdrmac I updated [README](https://github.com/x1unix/docker-go-mingw/blob/master/README.md) and project [example](https://github.com/x1unix/docker-go-mingw/blob/master/example/sqlite-app/Makefile). Please take a look!
